name: ci

on:
    pull_request:
        types: [closed]

env:
    IMAGE_PREFIX: ${{ github.repository }}

permissions:
    contents: write
    pull-requests: write
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        # if: github.event.pull_request.merged
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ghcr.io/${{ env.IMAGE_PREFIX }}:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: github.event.pull_request.merged == true && success()
        steps:
            - name: SSH into Server and Execute Commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_SERVER_HOST }}
                  username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
                  key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
                  script: |
                      cd xlock-workload
                      docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
                      docker compose -f docker-compose.backend.yml pull app
                      docker compose -f docker-compose.backend.yml down app
                      docker compose -f docker-compose.backend.yml up app -d --build
                      # Post deployment commands
                      docker system prune -f
                      docker logout ghcr.io
